name: Build Go projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19' 

    - name: Build hello
      run: |
        cd hello
        go mod tidy
        go build .

    # - name: Build helloserver
    #   run: |
    #     go mod tidy
    #     go build .

    # - name: Build outyet
    #   run: |
    #     go mod tidy
    #     go build ./outyet

