name: Build and Push Go Artifact to Nexus (Dev)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Build hello
      run: |
        cd hello
        go mod tidy
        go build .
      
    - name: Set up Nexus credentials
      run: |
        echo 'NEXUS_USERNAME=admin' >> $GITHUB_ENV
        echo 'NEXUS_PASSWORD=sothisismypassword,.000' >> $GITHUB_ENV
        echo 'NEXUS_BASE_URL=http://localhost:8081' >> $GITHUB_ENV

    - name: Publish Artifact to Nexus
      run: |
        curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file hello http://localhost:8081/#$NEXUS_USERNAME/repository/repositories:dev
